# Generated by Django 3.1.3 on 2021-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210113_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='comments',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
