# Generated by Django 3.1.3 on 2021-03-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20210301_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default=None, max_length=300, null=True, verbose_name='Комментарий'),
        ),
    ]
