# Generated by Django 3.1.3 on 2021-03-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
    ]
