# Generated by Django 3.1.3 on 2021-03-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_remove_boxsizes_e'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
