# Generated by Django 3.1.3 on 2021-03-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.TextField(default=None, max_length=300, null=True, verbose_name='Комментарий'),
        ),
    ]
